import type { Audiencia, Pendencia, Processo, ProximaAcao } from "./dominio";

/**
 * DADOS FICTÍCIOS — apenas para demonstração da interface.
 * Nenhum nome, número de processo ou documento real é utilizado aqui.
 */

const S = {
  reuPreso: { tipo: "reu-preso", rotulo: "Réu preso", severidade: "urgente" },
  temporaria: {
    tipo: "prisao-temporaria",
    rotulo: "Prisão temporária",
    severidade: "urgente",
  },
  semMov: {
    tipo: "sem-movimentacao",
    rotulo: "+100 dias sem movimentação",
    severidade: "atencao",
  },
  audProx: {
    tipo: "audiencia-proxima",
    rotulo: "Audiência próxima",
    severidade: "alerta",
  },
  audDist: {
    tipo: "audiencia-distante",
    rotulo: "Audiência em data distante",
    severidade: "info",
  },
  pendencia: { tipo: "pendencia", rotulo: "Pendência", severidade: "atencao" },
  prazo: { tipo: "prazo-proximo", rotulo: "Prazo próximo", severidade: "alerta" },
} as const satisfies Record<string, Processo["sinalizadores"][number]>;

export const PROCESSOS: Processo[] = [
  {
    id: "p1",
    numero: "0000101-45.2026.8.05.0000",
    classe: "Ação Penal",
    assunto: "Crime contra o patrimônio",
    fase: "Instrução",
    ultimaMovimentacao: "2026-09-18",
    descricaoUltimaMovimentacao: "Juntada de certidão de oficial de justiça",
    diasSemMovimentacao: 6,
    proximaAudiencia: "2026-09-30",
    proximaProvidencia: "Conferir intimação das testemunhas",
    responsavel: "Servidor A",
    sinalizadores: [S.reuPreso, S.audProx],
  },
  {
    id: "p2",
    numero: "0000212-77.2026.8.05.0000",
    classe: "Ação Penal",
    assunto: "Tráfico de entorpecentes",
    fase: "Instrução",
    ultimaMovimentacao: "2026-05-02",
    descricaoUltimaMovimentacao: "Conclusos para despacho",
    diasSemMovimentacao: 145,
    proximaAudiencia: "2027-02-11",
    proximaProvidencia: "Certificar decurso de prazo e fazer conclusão",
    responsavel: "Servidor B",
    sinalizadores: [S.reuPreso, S.semMov, S.audDist],
  },
  {
    id: "p3",
    numero: "0000333-10.2026.8.05.0000",
    classe: "Inquérito Policial",
    assunto: "Investigação em curso",
    fase: "Investigação",
    ultimaMovimentacao: "2026-09-21",
    descricaoUltimaMovimentacao: "Decretada prisão temporária",
    diasSemMovimentacao: 3,
    proximaAudiencia: null,
    proximaProvidencia: "Controlar prazo da prisão temporária (vence em 5 dias)",
    responsavel: "Servidor A",
    sinalizadores: [S.temporaria, S.prazo],
  },
  {
    id: "p4",
    numero: "0000474-02.2026.8.05.0000",
    classe: "Ação Penal",
    assunto: "Crime contra a pessoa",
    fase: "Instrução",
    ultimaMovimentacao: "2026-04-11",
    descricaoUltimaMovimentacao: "Expedida carta precatória",
    diasSemMovimentacao: 166,
    proximaAudiencia: null,
    proximaProvidencia: "Conferir cumprimento de carta precatória",
    responsavel: "Servidor C",
    sinalizadores: [S.semMov, S.pendencia],
  },
  {
    id: "p5",
    numero: "0000585-63.2026.8.05.0000",
    classe: "Execução Penal",
    assunto: "Execução de pena privativa de liberdade",
    fase: "Execução",
    ultimaMovimentacao: "2026-09-12",
    descricaoUltimaMovimentacao: "Juntada de atestado de pena",
    diasSemMovimentacao: 12,
    proximaAudiencia: "2026-10-06",
    proximaProvidencia: "Cumprir despacho de fl. anterior",
    responsavel: "Servidor B",
    sinalizadores: [S.reuPreso, S.audProx, S.pendencia],
  },
  {
    id: "p6",
    numero: "0000696-21.2026.8.05.0000",
    classe: "Ação Penal",
    assunto: "Crime de trânsito",
    fase: "Sentença",
    ultimaMovimentacao: "2026-09-08",
    descricaoUltimaMovimentacao: "Alegações finais da defesa",
    diasSemMovimentacao: 16,
    proximaAudiencia: null,
    proximaProvidencia: "Fazer conclusão para sentença",
    responsavel: "Servidor C",
    sinalizadores: [S.prazo],
  },
  {
    id: "p7",
    numero: "0000707-88.2026.8.05.0000",
    classe: "Ação Penal",
    assunto: "Violência doméstica",
    fase: "Instrução",
    ultimaMovimentacao: "2026-09-02",
    descricaoUltimaMovimentacao: "Designada audiência de instrução",
    diasSemMovimentacao: 22,
    proximaAudiencia: "2026-09-29",
    proximaProvidencia: "Expedir mandado de intimação da vítima",
    responsavel: "Servidor A",
    sinalizadores: [S.audProx, S.pendencia],
  },
  {
    id: "p8",
    numero: "0000818-35.2026.8.05.0000",
    classe: "Ação Penal",
    assunto: "Crime contra o patrimônio",
    fase: "Citação",
    ultimaMovimentacao: "2026-03-30",
    descricaoUltimaMovimentacao: "Expedido mandado de citação",
    diasSemMovimentacao: 178,
    proximaAudiencia: "2027-01-20",
    proximaProvidencia: "Verificar cumprimento do mandado de citação",
    responsavel: "Servidor B",
    sinalizadores: [S.semMov, S.audDist],
  },
];

export const PENDENCIAS: Pendencia[] = [
  {
    id: "d1",
    processoNumero: "0000474-02.2026.8.05.0000",
    descricao: "Carta precatória sem devolução há mais de 90 dias",
    prazo: "2026-09-28",
    severidade: "atencao",
  },
  {
    id: "d2",
    processoNumero: "0000585-63.2026.8.05.0000",
    descricao: "Atestado de pena pendente de conferência",
    prazo: "2026-10-02",
    severidade: "alerta",
  },
  {
    id: "d3",
    processoNumero: "0000707-88.2026.8.05.0000",
    descricao: "Intimação da vítima não confirmada",
    prazo: "2026-09-26",
    severidade: "urgente",
  },
  {
    id: "d4",
    processoNumero: "0000212-77.2026.8.05.0000",
    descricao: "Ausência de certidão de decurso de prazo",
    prazo: null,
    severidade: "atencao",
  },
];

export const PROXIMAS_ACOES: ProximaAcao[] = [
  {
    id: "a1",
    descricao: "Conferir cumprimento de carta precatória",
    processoNumero: "0000474-02.2026.8.05.0000",
    prazo: "2026-09-26",
    severidade: "atencao",
  },
  {
    id: "a2",
    descricao: "Certificar decurso de prazo",
    processoNumero: "0000212-77.2026.8.05.0000",
    prazo: "2026-09-25",
    severidade: "urgente",
  },
  {
    id: "a3",
    descricao: "Verificar intimação",
    processoNumero: "0000707-88.2026.8.05.0000",
    prazo: "2026-09-26",
    severidade: "urgente",
  },
  {
    id: "a4",
    descricao: "Cumprir despacho",
    processoNumero: "0000585-63.2026.8.05.0000",
    prazo: "2026-09-29",
    severidade: "alerta",
  },
  {
    id: "a5",
    descricao: "Conferir audiência",
    processoNumero: "0000101-45.2026.8.05.0000",
    prazo: "2026-09-29",
    severidade: "alerta",
  },
  {
    id: "a6",
    descricao: "Expedir mandado",
    processoNumero: "0000707-88.2026.8.05.0000",
    prazo: "2026-10-01",
    severidade: "info",
  },
];

export const AUDIENCIAS: Audiencia[] = [
  {
    id: "h1",
    processoNumero: "0000707-88.2026.8.05.0000",
    tipo: "Instrução e julgamento",
    data: "2026-09-29",
    local: "Sala de audiências 1",
    situacao: "Designada",
  },
  {
    id: "h2",
    processoNumero: "0000101-45.2026.8.05.0000",
    tipo: "Instrução e julgamento",
    data: "2026-09-30",
    local: "Sala de audiências 1",
    situacao: "Confirmada",
  },
  {
    id: "h3",
    processoNumero: "0000585-63.2026.8.05.0000",
    tipo: "Admonitória",
    data: "2026-10-06",
    local: "Sala de audiências 2",
    situacao: "Designada",
  },
  {
    id: "h4",
    processoNumero: "0000818-35.2026.8.05.0000",
    tipo: "Instrução e julgamento",
    data: "2027-01-20",
    local: "Sala de audiências 1",
    situacao: "Designada",
  },
  {
    id: "h5",
    processoNumero: "0000212-77.2026.8.05.0000",
    tipo: "Instrução e julgamento",
    data: "2027-02-11",
    local: "Sala de audiências 2",
    situacao: "Redesignada",
  },
];
