/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudienciasRouteImport } from './routes/audiencias'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as PrioridadesRouteImport } from './routes/prioridades'
import { Route as PrisoesTemporariasRouteImport } from './routes/prisoes-temporarias'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ReusPresosRouteImport } from './routes/reus-presos'
import { Route as SemMovimentacaoRouteImport } from './routes/sem-movimentacao'
import { Route as ProcessosIndexRouteImport } from './routes/processos.index'
import { Route as ProcessosIdRouteImport } from './routes/processos.$id'
import { Route as ProcessosNovoRouteImport } from './routes/processos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienciasRoute = AudienciasRouteImport.update({
  id: '/audiencias',
  path: '/audiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioridadesRoute = PrioridadesRouteImport.update({
  id: '/prioridades',
  path: '/prioridades',
  getParentRoute: () => rootRouteImport,
} as any)
const PrisoesTemporariasRoute = PrisoesTemporariasRouteImport.update({
  id: '/prisoes-temporarias',
  path: '/prisoes-temporarias',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReusPresosRoute = ReusPresosRouteImport.update({
  id: '/reus-presos',
  path: '/reus-presos',
  getParentRoute: () => rootRouteImport,
} as any)
const SemMovimentacaoRoute = SemMovimentacaoRouteImport.update({
  id: '/sem-movimentacao',
  path: '/sem-movimentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosIndexRoute = ProcessosIndexRouteImport.update({
  id: '/processos/',
  path: '/processos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosIdRoute = ProcessosIdRouteImport.update({
  id: '/processos/$id',
  path: '/processos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosNovoRoute = ProcessosNovoRouteImport.update({
  id: '/processos/novo',
  path: '/processos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiencias': typeof AudienciasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/pendencias': typeof PendenciasRoute
  '/prioridades': typeof PrioridadesRoute
  '/prisoes-temporarias': typeof PrisoesTemporariasRoute
  '/relatorios': typeof RelatoriosRoute
  '/reus-presos': typeof ReusPresosRoute
  '/sem-movimentacao': typeof SemMovimentacaoRoute
  '/processos/$id': typeof ProcessosIdRoute
  '/processos/novo': typeof ProcessosNovoRoute
  '/processos/': typeof ProcessosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiencias': typeof AudienciasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/pendencias': typeof PendenciasRoute
  '/prioridades': typeof PrioridadesRoute
  '/prisoes-temporarias': typeof PrisoesTemporariasRoute
  '/relatorios': typeof RelatoriosRoute
  '/reus-presos': typeof ReusPresosRoute
  '/sem-movimentacao': typeof SemMovimentacaoRoute
  '/processos/$id': typeof ProcessosIdRoute
  '/processos/novo': typeof ProcessosNovoRoute
  '/processos': typeof ProcessosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiencias': typeof AudienciasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/pendencias': typeof PendenciasRoute
  '/prioridades': typeof PrioridadesRoute
  '/prisoes-temporarias': typeof PrisoesTemporariasRoute
  '/relatorios': typeof RelatoriosRoute
  '/reus-presos': typeof ReusPresosRoute
  '/sem-movimentacao': typeof SemMovimentacaoRoute
  '/processos/$id': typeof ProcessosIdRoute
  '/processos/novo': typeof ProcessosNovoRoute
  '/processos/': typeof ProcessosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiencias'
    | '/configuracoes'
    | '/pendencias'
    | '/prioridades'
    | '/prisoes-temporarias'
    | '/relatorios'
    | '/reus-presos'
    | '/sem-movimentacao'
    | '/processos/$id'
    | '/processos/novo'
    | '/processos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiencias'
    | '/configuracoes'
    | '/pendencias'
    | '/prioridades'
    | '/prisoes-temporarias'
    | '/relatorios'
    | '/reus-presos'
    | '/sem-movimentacao'
    | '/processos/$id'
    | '/processos/novo'
    | '/processos'
  id:
    | '__root__'
    | '/'
    | '/audiencias'
    | '/configuracoes'
    | '/pendencias'
    | '/prioridades'
    | '/prisoes-temporarias'
    | '/relatorios'
    | '/reus-presos'
    | '/sem-movimentacao'
    | '/processos/$id'
    | '/processos/novo'
    | '/processos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudienciasRoute: typeof AudienciasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  PendenciasRoute: typeof PendenciasRoute
  PrioridadesRoute: typeof PrioridadesRoute
  PrisoesTemporariasRoute: typeof PrisoesTemporariasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ReusPresosRoute: typeof ReusPresosRoute
  SemMovimentacaoRoute: typeof SemMovimentacaoRoute
  ProcessosIdRoute: typeof ProcessosIdRoute
  ProcessosNovoRoute: typeof ProcessosNovoRoute
  ProcessosIndexRoute: typeof ProcessosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiencias': {
      id: '/audiencias'
      path: '/audiencias'
      fullPath: '/audiencias'
      preLoaderRoute: typeof AudienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prioridades': {
      id: '/prioridades'
      path: '/prioridades'
      fullPath: '/prioridades'
      preLoaderRoute: typeof PrioridadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prisoes-temporarias': {
      id: '/prisoes-temporarias'
      path: '/prisoes-temporarias'
      fullPath: '/prisoes-temporarias'
      preLoaderRoute: typeof PrisoesTemporariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reus-presos': {
      id: '/reus-presos'
      path: '/reus-presos'
      fullPath: '/reus-presos'
      preLoaderRoute: typeof ReusPresosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sem-movimentacao': {
      id: '/sem-movimentacao'
      path: '/sem-movimentacao'
      fullPath: '/sem-movimentacao'
      preLoaderRoute: typeof SemMovimentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/': {
      id: '/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof ProcessosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/$id': {
      id: '/processos/$id'
      path: '/processos/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof ProcessosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/novo': {
      id: '/processos/novo'
      path: '/processos/novo'
      fullPath: '/processos/novo'
      preLoaderRoute: typeof ProcessosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudienciasRoute: AudienciasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  PendenciasRoute: PendenciasRoute,
  PrioridadesRoute: PrioridadesRoute,
  PrisoesTemporariasRoute: PrisoesTemporariasRoute,
  RelatoriosRoute: RelatoriosRoute,
  ReusPresosRoute: ReusPresosRoute,
  SemMovimentacaoRoute: SemMovimentacaoRoute,
  ProcessosIdRoute: ProcessosIdRoute,
  ProcessosNovoRoute: ProcessosNovoRoute,
  ProcessosIndexRoute: ProcessosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
