/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAudienciasRouteImport } from './routes/_authenticated/audiencias'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedPrioridadesRouteImport } from './routes/_authenticated/prioridades'
import { Route as AuthenticatedPrisoesTemporariasRouteImport } from './routes/_authenticated/prisoes-temporarias'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReusPresosRouteImport } from './routes/_authenticated/reus-presos'
import { Route as AuthenticatedSemMovimentacaoRouteImport } from './routes/_authenticated/sem-movimentacao'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedConfiguracoesUsuariosRouteImport } from './routes/_authenticated/configuracoes.usuarios'
import { Route as AuthenticatedProcessosIndexRouteImport } from './routes/_authenticated/processos.index'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated/processos.$id'
import { Route as AuthenticatedProcessosNovoRouteImport } from './routes/_authenticated/processos.novo'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAudienciasRoute = AuthenticatedAudienciasRouteImport.update({
  id: '/audiencias',
  path: '/audiencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrioridadesRoute =
  AuthenticatedPrioridadesRouteImport.update({
    id: '/prioridades',
    path: '/prioridades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrisoesTemporariasRoute =
  AuthenticatedPrisoesTemporariasRouteImport.update({
    id: '/prisoes-temporarias',
    path: '/prisoes-temporarias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReusPresosRoute = AuthenticatedReusPresosRouteImport.update({
  id: '/reus-presos',
  path: '/reus-presos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSemMovimentacaoRoute =
  AuthenticatedSemMovimentacaoRouteImport.update({
    id: '/sem-movimentacao',
    path: '/sem-movimentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesUsuariosRoute =
  AuthenticatedConfiguracoesUsuariosRouteImport.update({
    id: '/configuracoes/usuarios',
    path: '/configuracoes/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosIndexRoute =
  AuthenticatedProcessosIndexRouteImport.update({
    id: '/processos/',
    path: '/processos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/processos/$id',
    path: '/processos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosNovoRoute =
  AuthenticatedProcessosNovoRouteImport.update({
    id: '/processos/novo',
    path: '/processos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/audiencias': typeof AuthenticatedAudienciasRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/prioridades': typeof AuthenticatedPrioridadesRoute
  '/prisoes-temporarias': typeof AuthenticatedPrisoesTemporariasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reus-presos': typeof AuthenticatedReusPresosRoute
  '/sem-movimentacao': typeof AuthenticatedSemMovimentacaoRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/processos/novo': typeof AuthenticatedProcessosNovoRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/processos/': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/audiencias': typeof AuthenticatedAudienciasRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/prioridades': typeof AuthenticatedPrioridadesRoute
  '/prisoes-temporarias': typeof AuthenticatedPrisoesTemporariasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reus-presos': typeof AuthenticatedReusPresosRoute
  '/sem-movimentacao': typeof AuthenticatedSemMovimentacaoRoute
  '/': typeof AuthenticatedIndexRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/processos/novo': typeof AuthenticatedProcessosNovoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/processos': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audiencias': typeof AuthenticatedAudienciasRoute
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/prioridades': typeof AuthenticatedPrioridadesRoute
  '/_authenticated/prisoes-temporarias': typeof AuthenticatedPrisoesTemporariasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/reus-presos': typeof AuthenticatedReusPresosRoute
  '/_authenticated/sem-movimentacao': typeof AuthenticatedSemMovimentacaoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/_authenticated/processos/novo': typeof AuthenticatedProcessosNovoRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/processos/': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audiencias'
    | '/pendencias'
    | '/prioridades'
    | '/prisoes-temporarias'
    | '/relatorios'
    | '/reus-presos'
    | '/sem-movimentacao'
    | '/configuracoes/usuarios'
    | '/processos/$id'
    | '/processos/novo'
    | '/configuracoes/'
    | '/processos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/audiencias'
    | '/pendencias'
    | '/prioridades'
    | '/prisoes-temporarias'
    | '/relatorios'
    | '/reus-presos'
    | '/sem-movimentacao'
    | '/'
    | '/configuracoes/usuarios'
    | '/processos/$id'
    | '/processos/novo'
    | '/configuracoes'
    | '/processos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audiencias'
    | '/_authenticated/pendencias'
    | '/_authenticated/prioridades'
    | '/_authenticated/prisoes-temporarias'
    | '/_authenticated/relatorios'
    | '/_authenticated/reus-presos'
    | '/_authenticated/sem-movimentacao'
    | '/_authenticated/'
    | '/_authenticated/configuracoes/usuarios'
    | '/_authenticated/processos/$id'
    | '/_authenticated/processos/novo'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/processos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audiencias': {
      id: '/_authenticated/audiencias'
      path: '/audiencias'
      fullPath: '/audiencias'
      preLoaderRoute: typeof AuthenticatedAudienciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prioridades': {
      id: '/_authenticated/prioridades'
      path: '/prioridades'
      fullPath: '/prioridades'
      preLoaderRoute: typeof AuthenticatedPrioridadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prisoes-temporarias': {
      id: '/_authenticated/prisoes-temporarias'
      path: '/prisoes-temporarias'
      fullPath: '/prisoes-temporarias'
      preLoaderRoute: typeof AuthenticatedPrisoesTemporariasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reus-presos': {
      id: '/_authenticated/reus-presos'
      path: '/reus-presos'
      fullPath: '/reus-presos'
      preLoaderRoute: typeof AuthenticatedReusPresosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sem-movimentacao': {
      id: '/_authenticated/sem-movimentacao'
      path: '/sem-movimentacao'
      fullPath: '/sem-movimentacao'
      preLoaderRoute: typeof AuthenticatedSemMovimentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/usuarios': {
      id: '/_authenticated/configuracoes/usuarios'
      path: '/configuracoes/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/': {
      id: '/_authenticated/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof AuthenticatedProcessosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/processos/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/novo': {
      id: '/_authenticated/processos/novo'
      path: '/processos/novo'
      fullPath: '/processos/novo'
      preLoaderRoute: typeof AuthenticatedProcessosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAudienciasRoute: typeof AuthenticatedAudienciasRoute
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedPrioridadesRoute: typeof AuthenticatedPrioridadesRoute
  AuthenticatedPrisoesTemporariasRoute: typeof AuthenticatedPrisoesTemporariasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedReusPresosRoute: typeof AuthenticatedReusPresosRoute
  AuthenticatedSemMovimentacaoRoute: typeof AuthenticatedSemMovimentacaoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedConfiguracoesUsuariosRoute: typeof AuthenticatedConfiguracoesUsuariosRoute
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
  AuthenticatedProcessosNovoRoute: typeof AuthenticatedProcessosNovoRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
  AuthenticatedProcessosIndexRoute: typeof AuthenticatedProcessosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAudienciasRoute: AuthenticatedAudienciasRoute,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedPrioridadesRoute: AuthenticatedPrioridadesRoute,
  AuthenticatedPrisoesTemporariasRoute: AuthenticatedPrisoesTemporariasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedReusPresosRoute: AuthenticatedReusPresosRoute,
  AuthenticatedSemMovimentacaoRoute: AuthenticatedSemMovimentacaoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedConfiguracoesUsuariosRoute:
    AuthenticatedConfiguracoesUsuariosRoute,
  AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
  AuthenticatedProcessosNovoRoute: AuthenticatedProcessosNovoRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  AuthenticatedProcessosIndexRoute: AuthenticatedProcessosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
